name: dartz_extensions
description: "Extensions for the dartz package."
version: 0.1.0
homepage: https://github.com/Dri3xCz/dartz_extensions

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  dartz: ^0.10.1

dev_dependencies:
  test: ">=1.17.1"
  lints: ^6.1.0



